imports:
    - { resource: config_dev.yml }

framework:
    test: ~

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        driver: "pdo_sqlite"
        path: "%kernel.cache_dir%/db.sqlite"

web_profiler:
    toolbar: false
    intercept_redirects: false
